#general settings
name: HoCo STEM
email: hocostem@gmail.hocostem
description: "Welcome to HoCoSTEM, a resource for students to learn more about how to pursue a career in STEM."
baseurl: ""
url: ""
mailchimp-list: "https://github.us4.list-manage.com/subscribe/post?u=4a3b33b90c977ad58a46565f8&amp;id=d6438239c1"
